### ISSUE TITLE
NavigationRail loses focus when SubItem is selected.

### ISSUE THREAD

**Issue by saklanmazozgur** [Patrick386/rail_sub_menu_demo#1]
Hello,

First of all, thank you for the work. NavigationRail loses focus if a subitem is clicked. This is best understood when NavigationRailLabelType.selected is selected. Is there a solution for this?

**Comment by Patrick386** [comment]
> Hello,
> 
> First of all, thank you for the work. NavigationRail loses focus if a subitem is clicked. This is best understood when NavigationRailLabelType.selected is selected. Is there a solution for this?

The demo app has some issues and is only at a basic sample level. 
Currently, the submenu widget has improved on several issues and the animation has also been changed. However, there are still some issues that need to be addressed.(flutter hot reload ) For example, when refreshing the browser, the selected NavigationRail position is reset. This is something that needs to be improved. This week, I have a lot on my schedule, so it will be difficult to update it. I will update it soon. Please refer to the video. Thank you.

https://user-images.githubusercontent.com/49754877/233885195-e84ec838-3c28-4fc8-bd15-862e892aed86.mov

**Comment by Patrick386** [comment]
I resolved the issue of "NavigationRail loses focus if a subitem is clicked" and the problem of Nail focus disappearing when hot-reloading.

**Comment by saklanmaz** [comment]
> I resolved the issue of "NavigationRail loses focus if a subitem is clicked" and the problem of Nail focus disappearing when hot-reloading.

Thank you. I'm waiting for the update.
