### ISSUE TITLE
The left side of the page is not clickable.

### ISSUE THREAD

**Issue by saklanmazozgur** [Patrick386/rail_sub_menu_demo#3]
After the SubItem menu is opened, the left side of the page is not clickable. When you put a button to the far left, you will see that it is not clicked.

**Comment by Patrick386** [comment]
> After the SubItem menu is opened, the left side of the page is not clickable. When you put a button to the far left, you will see that it is not clicked.

The new version has improved several features such as the structure, animation, and menu selection, compared to the previous demo version. If you wish, I can update it during next week.

**Comment by saklanmaz** [comment]
Thank you for your quick reply. I'm waiting for the update. The sooner you update it, the better for me.

**Comment by Patrick386** [comment]
> Thank you for your quick reply. I'm waiting for the update. The sooner you update it, the better for me.

We have updated to a new version. Please let us know if there are any issues. thank you.
